# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 171, 31))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 255, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel:hover{\n"
"    background-color:rgb(142, 253, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 255);\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 100, 211, 51))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 255, 0);\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgb(142, 253, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 255);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 100, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 25, 5);\n"
"    border: 2px solid;\n"
"    border-color: rgb(255, 255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0,0,0);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:26px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 100, 211, 51))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 255, 0);\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgb(142, 253, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 255);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 100, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 25, 5);\n"
"    border: 2px solid;\n"
"    border-color: rgb(255, 255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0,0,0);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:26px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 180, 281, 211))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 255, 0);\n"
"}\n"
"QTextBrowser:hover{\n"
"    background-color:rgb(142, 253, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 255);\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(320, 180, 281, 211))
        self.textBrowser_2.setStyleSheet("QTextBrowser{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 255, 0);\n"
"}\n"
"QTextBrowser:hover{\n"
"    background-color:rgb(142, 253, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 255);\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ceny walut w NBP"))
        self.pushButton.setText(_translate("MainWindow", "ok"))
        self.pushButton_2.setText(_translate("MainWindow", "ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
